f=open("quote.txt","r")
print("read method:")
print(f.read(6))
f.seek(0)
print("\nreadline method:")
print(f.readline(8))
f.seek(0)
print("\nreadlines method:")
print(f.readlines())
f.close()
